#!/usr/bin/env bash
# post-qa-checklist.sh
# Posts a structured QA checklist comment on a PR.
# Usage: GH_TOKEN=<token> REPO=<owner/repo> bash post-qa-checklist.sh <pr_number>

set -euo pipefail

PR_NUMBER="${1:?Usage: post-qa-checklist.sh <pr_number>}"
REPO="${REPO:-$(gh repo view --json nameWithOwner --jq '.nameWithOwner')}"

echo "Posting QA checklist for PR #$PR_NUMBER..."

# Get PR details
PR_DATA=$(gh pr view "$PR_NUMBER" --repo "$REPO" --json title,body,headRefName,additions,deletions,changedFiles 2>/dev/null || echo "{}")

PR_TITLE=$(echo "$PR_DATA" | jq -r '.title')
PR_BODY=$(echo "$PR_DATA" | jq -r '.body')
PR_BRANCH=$(echo "$PR_DATA" | jq -r '.headRefName')
ADDITIONS=$(echo "$PR_DATA" | jq -r '.additions')
DELETIONS=$(echo "$PR_DATA" | jq -r '.deletions')
CHANGED_FILES=$(echo "$PR_DATA" | jq -r '.changedFiles')

# Extract linked issue number
ISSUE_NUMBER=$(echo "$PR_BODY" | grep -oP '(?i)(closes|fixes|resolves)\s+#\K[0-9]+' | head -1 || echo "")
EPIC_NUMBER=$(echo "$PR_BODY" | grep -oP '(?i)part of\s+#\K[0-9]+' | head -1 || echo "")

# Get issue acceptance criteria if linked
ACCEPTANCE_CRITERIA=""
if [ -n "$ISSUE_NUMBER" ]; then
  ISSUE_BODY=$(gh issue view "$ISSUE_NUMBER" --repo "$REPO" --json body --jq '.body' 2>/dev/null || echo "")
  ACCEPTANCE_CRITERIA=$(echo "$ISSUE_BODY" | grep -A 50 "Acceptance Criteria" | grep "^\- \[" | head -10 || echo "")
fi

# Format acceptance criteria for QA checklist
CRITERIA_CHECKLIST=""
if [ -n "$ACCEPTANCE_CRITERIA" ]; then
  CRITERIA_CHECKLIST=$(echo "$ACCEPTANCE_CRITERIA" | sed 's/^\- \[x\]/- [x]/i; s/^\- \[ \]/- [ ]/i')
else
  CRITERIA_CHECKLIST="- [ ] Verify implementation matches issue description\n- [ ] No regressions introduced"
fi

# Build QA comment
QA_COMMENT="## 🔍 QA Agent – Code Review Checklist

**PR**: #$PR_NUMBER – $PR_TITLE
**Branch**: \`$PR_BRANCH\`
**Linked Issue**: ${ISSUE_NUMBER:+#$ISSUE_NUMBER}${EPIC_NUMBER:+ (Part of #$EPIC_NUMBER)}
**Diff**: +$ADDITIONS / -$DELETIONS lines across $CHANGED_FILES file(s)

---

### ✅ Automated Checks
*Check the Actions tab for CI results*
- [ ] All tests pass
- [ ] Linting passes
- [ ] Build succeeds

### 📋 Acceptance Criteria
$CRITERIA_CHECKLIST

### 🔍 Code Review
- [ ] Implementation matches the sub-issue description
- [ ] No debug code or temporary workarounds left
- [ ] No unintended scope creep
- [ ] Code follows repository conventions
- [ ] Tests added or updated as appropriate
- [ ] Documentation updated if applicable

### 🔐 Security
- [ ] No secrets or sensitive data in the code
- [ ] Input validation is appropriate
- [ ] No obvious security vulnerabilities

---

### 🔴 HUMAN ACTION REQUIRED

Please review the checklist above and:
- ✅ **Approve** the PR if everything is good → triggers automatic merge and release
- ❌ **Request changes** if something needs fixing → sub-issue is moved back to In Progress

> *This checklist was automatically generated by the QA Agent. See \`.github/agents/qa-agent.md\`.*"

gh pr comment "$PR_NUMBER" --repo "$REPO" --body "$QA_COMMENT"
echo "✅ QA checklist posted on PR #$PR_NUMBER"
